--spring.application.name=template
server.port=8080
spring.config.import=
spring.cloud.config.enabled=false
url.cors=*
endpoids.excluded=/actuator/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html\

spring.database.driverClassName=org.postgresql.Driver
spring.database.url=jdbc:postgresql://localhost:5432/db_portal
spring.database.username=postgres
spring.database.password=admin  
--spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 

