--spring.application.name=template
server.port=8080
spring.config.import=
spring.cloud.config.enabled=false
url.cors=*
endpoids.excluded=/actuator/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html\

spring.database.driverClassName=org.postgresql.Driver
spring.database.url=jdbc:postgresql://localhost:5432/db_portal
spring.database.username=postgres
spring.database.password=admin  
--spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect\

# --- Actuator básico ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# --- Puerto opcional para management (si quieres separarlo del puerto principal) ---
management.server.port=8081

# --- Seguridad opcional (si usas Spring Security) ---
# management.endpoints.web.exposure.exclude=shutdown
# management.endpoint.shutdown.enabled=true

# --- Información personalizada (se muestra en /actuator/info) ---
info.app.name=template
info.app.description=Aplicación demo con Actuator
info.app.version=1.0.0

# --- Métricas ---
management.metrics.tags.application=template
management.metrics.export.prometheus.enabled=true 

